services:
  user-db:
    image: postgres:16-alpine
    container_name: user-db
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: user_service_app
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

volumes:
  user_db_data: