spring.datasource.url=jdbc:h2:mem:user_service_test_db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.flyway.enabled=false

jwt.secret=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
jwt.expiration-ms=86400000