server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://user-db:5432/user_service_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user_service_app}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}