spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

jwt.secret=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
jwt.expiration-ms=86400000